# --- Typescript/JavaScript

[[language]]
name = "typescript"
language-servers = [ "oxc", "typescript-language-server" ]
formatter = { command = "oxfmt", args = ["--stdin-filepath", "dummy.ts"] }
auto-format = true

[[language]]
name = "javascript"
language-servers = [ "oxc", "typescript-language-server" ]
formatter = { command = "oxfmt", args = ["--stdin-filepath", "dummy.js"] }
auto-format = true

[[language]]
name = "json"
formatter = { command = "oxfmt", args = ["--stdin-filepath", "dummy.json"] }

[language-server.oxc]
command = "oxlint"
args =  ["--lsp-server"]

# --- C

[[language]]
name = "c"
auto-format = true
formatter = { command = "clang-format", args = ["--style=file"]}

# --- Python

[[language]]
name = "python"
language-servers = ["ruff"]
auto-format = true

[language-server.ruff]
command = "ruff"
args = ["server"]

# --- LaTeX

[[language]]
name = "latex"
language-servers = [ "texlab" , "ltex-ls-plus" ]

[language-server.ltex]
command = "ltex-ls-plus"

[language-server.ltex.config.ltex.dictionary]
"en-US" = ["ewwe","flaberrasted"]

[language-server.texlab]
command = "texlab"

[language-server.texlab.config.texlab.build]
onSave = true
forwardSearchAfter = true
 executable = "latexmk"
 args = [
  "-pdf",
  "-interaction=nonstopmode",
  "-synctex=1",
  "-shell-escape",
  "%f"
  ]

[language-server.texlab.config.texlab.forwardSearch]
executable = "zathura"
args = [ "--synctex-forward", "%l:%c:%f", "%p" ]

[language-server.texlab.config.texlab.chktex]
onOpenAndSave = true
onEdit = true
